#!/usr/bin/python
# -*- coding: utf-8 -*-
import urllib
import urllib2,re

page = 1
url = 'http://www.njgs.gov.cn/' + str(page)
user_agent = 'Mozilla/4.0 (compatible; MSIE 5.5; Windows NT)'
headers = { 'User-Agent' : user_agent }
try:
    request = urllib2.Request(url,headers = headers)
    response = urllib2.urlopen(request)
    #print response.read()
    #匹配信息
    content = response.read().decode('utf-8')
    pattern = re.compile('''<tr class="qycx2">[\s]+<td>\d+</td>[\s]+
    <td>[\u4e00-\u9fa5]{0,20}</td>[\s]+<td>[\u4e00-\u9fa5]{0,20}</td>
    [\s]+<td></td>[\s]+<td>([0-9]{3}[1-9]|[0-9]{2}[1-9][0-9]{1}|[0-9]{1}
    [1-9][0-9]{2}|[1-9][0-9]{3})/(((0[13578]|1[02])/(0[1-9]|[12][0-9]|3[01]))
    |((0[469]|11)/(0[1-9]|[12][0-9]|30))|(02-(0[1-9]|[1][0-9]|2[0-8])))</td>
    [\s]+</tr>''',re.S)
    company_info = re.findall(pattern,content)
    for company in company_info:
        print company
except urllib2.URLError, e:
    if hasattr(e,"code"):
        print e.code
    if hasattr(e,"reason"):
        print e.reason
    response = urllib2.urlopen(request)
    #print response.read()
    #匹配信息
    content = response.read().decode('utf-8')
    pattern = re.compile('''<tr class="qycx2">[\s]+<td>\d+</td>[\s]+
    <td>[\u4e00-\u9fa5]{0,20}</td>[\s]+<td>[\u4e00-\u9fa5]{0,20}</td>
    [\s]+<td></td>[\s]+<td>([0-9]{3}[1-9]|[0-9]{2}[1-9][0-9]{1}|[0-9]{1}
    [1-9][0-9]{2}|[1-9][0-9]{3})/(((0[13578]|1[02])/(0[1-9]|[12][0-9]|3[01]))
    |((0[469]|11)/(0[1-9]|[12][0-9]|30))|(02-(0[1-9]|[1][0-9]|2[0-8])))</td>
    [\s]+</tr>''',re.S)
    company_info = re.findall(pattern,content)
    for company in company_info:
        print company
except urllib2.URLError, e:
    if hasattr(e,"code"):
        print e.code
    if hasattr(e,"reason"):
        print e.reason


